export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_FAIL = "REGISTER_STUDENT_FAIL";

export const GET_STUDENT_APPROVAL_REQUEST = "GET_STUDENT_APPROVAL_REQUEST";
export const GET_STUDENT_APPROVAL_SUCCESS = "GET_STUDENT_APPROVAL_SUCCESS";
export const GET_STUDENT_APPROVAL_FAIL = "GET_STUDENT_APPROVAL_FAIL";

export const STUDENT_APPROVAL_ACCEPT_REQUEST =
  "STUDENT_APPROVAL_ACCEPT_REQUEST";
export const STUDENT_APPROVAL_ACCEPT_SUCCESS =
  "STUDENT_APPROVAL_ACCEPT_SUCCESS";
export const STUDENT_APPROVAL_ACCEPT_FAIL = "STUDENT_APPROVAL_ACCEPT_FAIL";

export const STUDENT_APPROVAL_REJECT_REQUEST =
  "STUDENT_APPROVAL_REJECT_REQUEST";
export const STUDENT_APPROVAL_REJECT_SUCCESS =
  "STUDENT_APPROVAL_REJECT_SUCCESS";
export const STUDENT_APPROVAL_REJECT_FAIL = "STUDENT_APPROVAL_REJECT_FAIL";

export const REGISTER_TEACHER_REQUEST = "REGISTER_TEACHER_REQUEST";
export const REGISTER_TEACHER_SUCCESS = "REGISTER_TEACHER_SUCCESS";
export const REGISTER_TEACHER_FAIL = "REGISTER_TEACHER_FAIL";

export const GET_TEACHER_APPROVAL_REQUEST = "GET_TEACHER_APPROVAL_REQUEST";
export const GET_TEACHER_APPROVAL_SUCCESS = "GET_TEACHER_APPROVAL_SUCCESS";
export const GET_TEACHER_APPROVAL_FAIL = "GET_TEACHER_APPROVAL_FAIL";

export const TEACHER_APPROVAL_ACCEPT_REQUEST =
  "TEACHER_APPROVAL_ACCEPT_REQUEST";
export const TEACHER_APPROVAL_ACCEPT_SUCCESS =
  "TEACHER_APPROVAL_ACCEPT_SUCCESS";
export const TEACHER_APPROVAL_ACCEPT_FAIL = "TEACHER_APPROVAL_ACCEPT_FAIL";

export const TEACHER_APPROVAL_REJECT_REQUEST =
  "TEACHER_APPROVAL_REJECT_REQUEST";
export const TEACHER_APPROVAL_REJECT_SUCCESS =
  "TEACHER_APPROVAL_REJECT_SUCCESS";
export const TEACHER_APPROVAL_REJECT_FAIL = "TEACHER_APPROVAL_REJECT_FAIL";