export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_FAIL = "REGISTER_STUDENT_FAIL";

export const LOGIN_STUDENT_REQUEST = "LOGIN_STUDENT_REQUEST";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";
export const LOGIN_STUDENT_FAIL = "LOGIN_STUDENT_FAIL";

export const LOGOUT_STUDENT_SUCCESS = "LOGOUT_STUDENT_SUCCESS";
export const LOGOUT_STUDENT_FAIL = "LOGOUT_STUDENT_FAIL";

export const LOAD_STUDENT_REQUEST = "LOAD_STUDENT_REQUEST";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const LOAD_STUDENT_FAIL = "LOAD_STUDENT_FAIL";

export const COURSE_STUDENT_REQUEST = "COURSE_STUDENT_REQUEST";
export const COURSE_STUDENT_SUCCESS = "COURSE_STUDENT_SUCCESS";
export const COURSE_STUDENT_FAIL = "COURSE_STUDENT_FAIL";
