export const LOGIN_STUDENT_REQUEST = "LOGIN_STUDENT_REQUEST";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";
export const LOGIN_STUDENT_FAIL = "LOGIN_STUDENT_FAIL";

export const LOGOUT_STUDENT_SUCCESS = "LOGOUT_STUDENT_SUCCESS";
export const LOGOUT_STUDENT_FAIL = "LOGOUT_STUDENT_FAIL";

export const LOAD_STUDENT_REQUEST = "LOAD_STUDENT_REQUEST";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const LOAD_STUDENT_FAIL = "LOAD_STUDENT_FAIL";

export const COURSE_STUDENT_REQUEST = "COURSE_STUDENT_REQUEST";
export const COURSE_STUDENT_SUCCESS = "COURSE_STUDENT_SUCCESS";
export const COURSE_STUDENT_FAIL = "COURSE_STUDENT_FAIL";

export const SUBMIT_MARKS_REQUEST = "SUBMIT_MARKS_REQUEST";
export const SUBMIT_MARKS_SUCCESS = "SUBMIT_MARKS_SUCCESS";
export const SUBMIT_MARKS_FAIL = "SUBMIT_MARKS_FAIL";

export const SUBMIT_FEES_REQUEST = "SUBMIT_FEES_REQUEST";
export const SUBMIT_FEES_SUCCESS = "SUBMIT_FEES_SUCCESS";
export const SUBMIT_FEES_FAIL = "SUBMIT_FEES_FAIL";

export const SUBMIT_COURSE_REQUEST = "SUBMIT_COURSE_REQUEST";
export const SUBMIT_COURSE_SUCCESS = "SUBMIT_COURSE_SUCCESS";
export const SUBMIT_COURSE_FAIL = "SUBMIT_COURSE_FAIL";

export const SUBMIT_SCHOLARSHIP_REQUEST = "SUBMIT_SCHOLARSHIP_REQUEST";
export const SUBMIT_SCHOLARSHIP_SUCCESS = "SUBMIT_SCHOLARSHIP_SUCCESS";
export const SUBMIT_SCHOLARSHIP_FAIL = "SUBMIT_SCHOLARSHIP_FAIL";

export const GET_STUDENT_SEMESTER_DEPARTMENT_REQUEST =
  "GET_STUDENT_SEMESTER_DEPARTMENT_REQUEST";
export const GET_STUDENT_SEMESTER_DEPARTMENT_SUCCESS =
  "GET_STUDENT_SEMESTER_DEPARTMENT_SUCCESS";
export const GET_STUDENT_SEMESTER_DEPARTMENT_FAIL = "SUBMIT_SCHOLARSHIP_FAIL";

export const COURSE_SUBJECT_LIST_REQUEST = "COURSE_SUBJECT_LIST_REQUEST";
export const COURSE_SUBJECT_LIST_SUCCESS = "COURSE_SUBJECT_LIST_SUCCESS";
export const COURSE_SUBJECT_LIST_FAIL = "COURSE_SUBJECT_LIST_FAIL";
