export const LOGIN_TEACHER_REQUEST = "LOGIN_TEACHER_REQUEST";
export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_SUCCESS";
export const LOGIN_TEACHER_FAIL = "LOGIN_TEACHER_FAIL";

export const LOGOUT_TEACHER_SUCCESS = "LOGOUT_TEACHER_SUCCESS";
export const LOGOUT_TEACHER_FAIL = "LOGOUT_TEACHER_FAIL";

export const LOAD_TEACHER_REQUEST = "LOAD_TEACHER_REQUEST";
export const LOAD_TEACHER_SUCCESS = "LOAD_TEACHER_SUCCESS";
export const LOAD_TEACHER_FAIL = "LOAD_TEACHER_FAIL";

export const COURSE_ACCEPT_REQUEST = "COURSE_ACCEPT_REQUEST";
export const COURSE_ACCEPT_SUCCESS = "COURSE_ACCEPT_SUCCESS";
export const COURSE_ACCEPT_FAIL = "COURSE_ACCEPT_FAIL";

export const COURSE_REJECT_REQUEST = "COURSE_REJECT_REQUEST";
export const COURSE_REJECT_SUCCESS = "COURSE_REJECT_SUCCESS";
export const COURSE_REJECT_FAIL = "COURSE_REJECT_FAIL";

export const GET_COURSE_APPROVAL_REQUEST = "GET_COURSE_APPROVAL_REQUEST";
export const GET_COURSE_APPROVAL_SUCCESS = "GET_COURSE_APPROVAL_SUCCESS";
export const GET_COURSE_APPROVAL_FAIL = "GET_COURSE_APPROVAL_FAIL";

export const SCHOLARSHIP_ACCEPT_REQUEST = "SCHOLARSHIP_ACCEPT_REQUEST";
export const SCHOLARSHIP_ACCEPT_SUCCESS = "SCHOLARSHIP_ACCEPT_SUCCESS";
export const SCHOLARSHIP_ACCEPT_FAIL = "SCHOLARSHIP_ACCEPT_FAIL";

export const SCHOLARSHIP_REJECT_REQUEST = "SCHOLARSHIP_REJECT_REQUEST";
export const SCHOLARSHIP_REJECT_SUCCESS = "SCHOLARSHIP_REJECT_SUCCESS";
export const SCHOLARSHIP_REJECT_FAIL = "SCHOLARSHIP_REJECT_FAIL";

export const GET_SCHOLARSHIP_APPROVAL_REQUEST =
  "GET_SCHOLARSHIP_APPROVAL_REQUEST";
export const GET_SCHOLARSHIP_APPROVAL_SUCCESS =
  "GET_SCHOLARSHIP_APPROVAL_SUCCESS";
export const GET_SCHOLARSHIP_APPROVAL_FAIL = "GET_SCHOLARSHIP_APPROVAL_FAIL";

export const SUBMIT_ATTENDANCE_ENTRY_REQUEST =
  "SUBMIT_ATTENDANCE_ENTRY_REQUEST";
export const SUBMIT_ATTENDANCE_ENTRY_SUCCESS =
  "SUBMIT_ATTENDANCE_ENTRY_SUCCESS";
export const SUBMIT_ATTENDANCE_ENTRY_FAIL = "SUBMIT_ATTENDANCE_ENTRY_FAIL";

export const GET_ATTENDANCE_BY_SUBJECT_REQUEST =
  "GET_ATTENDANCE_BY_SUBJECT_REQUEST";
export const GET_ATTENDANCE_BY_SUBJECT_SUCCESS =
  "GET_ATTENDANCE_BY_SUBJECT_SUCCESS";
export const GET_ATTENDANCE_BY_SUBJECT_FAIL = "GET_ATTENDANCE_BY_SUBJECT_FAIL";

export const SUBMIT_MARKS_ENTRY_REQUEST = "SUBMIT_MARKS_ENTRY_REQUEST";
export const SUBMIT_MARKS_ENTRY_SUCCESS = "SUBMIT_MARKS_ENTRY_SUCCESS";
export const SUBMIT_MARKS_ENTRY_FAIL = "SUBMIT_MARKS_ENTRY_FAIL";

export const GET_MARKS_BY_SUBJECT_REQUEST = "GET_MARKS_BY_SUBJECT_REQUEST";
export const GET_MARKS_BY_SUBJECT_SUCCESS = "GET_MARKS_BY_SUBJECT_SUCCESS";
export const GET_MARKS_BY_SUBJECT_FAIL = "GET_MARKS_BY_SUBJECT_FAIL";

export const UPDATE_TEACHER_DETAILS_REQUEST = "UPDATE_TEACHER_DETAILS_REQUEST";
export const UPDATE_TEACHER_DETAILS_SUCCESS = "UPDATE_TEACHER_DETAILS_SUCCESS";
export const UPDATE_TEACHER_DETAILS_FAIL = "UPDATE_TEACHER_DETAILS_FAIL";
