export const LOGIN_TEACHER_REQUEST = "LOGIN_TEACHER_REQUEST";
export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_SUCCESS";
export const LOGIN_TEACHER_FAIL = "LOGIN_TEACHER_FAIL";

export const LOAD_TEACHER_REQUEST = "LOAD_TEACHER_REQUEST";
export const LOAD_TEACHER_SUCCESS = "LOAD_TEACHER_SUCCESS";
export const LOAD_TEACHER_FAIL = "LOAD_TEACHER_FAIL";
